### ISSUE TITLE
Update to the 2018 SDK

### ISSUE THREAD

**Issue by CrossVR** [gildor2/ActorX#2]
3ds Max 2018 has been released, so the ActorX package should be updated. If anyone reading this needs the ActorX plugin for 3ds Max 2018 right now you can download it here: [Max2018_x64.zip](https://github.com/gildor2/ActorX/files/1066373/Max2018_x64.zip)

**Comment by DemonRem** [comment]
what been changed?

**Comment by CrossVR** [comment]
Nothing changed, it's just compiled against the new SDK.

**Comment by iamjoeysox** [comment]
Can you link to the Maya version please?

**Comment by CrossVR** [comment]
There's nothing to link to, I never compiled a Maya version.

**Comment by gildor2** [comment]
I've added versions for Max 2018, Max 2019 and Maya 2018. Now I think this issue could be closed.
