### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by DemonRem** [gildor2/ActorX#3]

**Comment by DemonRem** [comment]
can I edit those source? and create pull?

**Comment by gildor2** [comment]
Sorry, I didn't understand you.

**Comment by DemonRem** [comment]
I mean when I try make a commit I have error say I need premission

**Comment by gildor2** [comment]
You can commit only to own repositories. To promote own changes to original repository, you should fork a repository, commit there, and then do a pull request. This is standard github (and git) practice.
