### ISSUE TITLE
Unsupported Version 7

### ISSUE THREAD

**Issue by ThymeParadox** [gildor2/ActorX#4]
Uppon opening Unsupported Version 7 appears next to all lines of code in the command line, and no files can be viewed in 3d or exported but I can see all paths and file names

**Comment by gildor2** [comment]
ActorX plugin is not opening anything. It's EXPORT of selected mesh and animation from 3ds Max.

**Comment by ThymeParadox** [comment]
Sorry ment to put this on umodel
