### ISSUE TITLE
Plans to update to 3DS Max 2022?

### ISSUE THREAD

**Issue by Yankshuru** [gildor2/ActorX#7]
Hi, there's plans to update to max 22?
Is much complicate port it? I'm asking because every max looks similar enough, I'm not programmer, but if it's a little change, maybe I can get it with some help...
Thanks!

**Comment by gildor2** [comment]
Hi.
I'm providing builds as soon as someone provides me SDK for requested version. Usually update for a new version requires just to rebuild the project, with no coding.

**Comment by Yankshuru** [comment]
> Hi.
> I'm providing builds as soon as someone provides me SDK for requested version. Usually update for a new version requires just to rebuild the project, with no coding.

Is this? https://drive.google.com/file/d/1p8NiHd3WabU4pk-2i5oewvSBSd0SHm2Y/view?usp=sharing

**Comment by gildor2** [comment]
Yes, thanks for files.
Provided a build for Max 2022.

**Comment by Yankshuru** [comment]
> Yes, thank.
> Provided a build for Max 2022.

Thanks a lot!
