### ISSUE TITLE
Importing the animation, breaks the skeletal mesh.

### ISSUE THREAD

**Issue by c0r37py** [gildor2/ActorX#8]
More details:
I have a skeletal mesh and 2 animations.
Importing the **animation1** works fine and the  **animation2**  doesn't.
To reproduce the issue on your end I can share the files with you for more investigation.

[Base_Skeleton.zip](https://github.com/gildor2/ActorX/files/7146951/Base_Skeleton.zip)
[animation 1.zip](https://github.com/gildor2/ActorX/files/7146952/animation.1.zip)
[animation 2.zip](https://github.com/gildor2/ActorX/files/7146953/animation.2.zip)

**Comment by gildor2** [comment]
This is EXPORTER. You can't IMPORT anything anywhere using it.

**Comment by c0r37py** [comment]
oh my bad, I was posting it on **UE viewer**, or **ActorX Importer** for **3DSmax** .
Thank you for correcting ) and why you don't have a git for https://www.gildor.org/projects/unactorx ?
the issue is happening with **ActorX importer**  or maybe UModel is not exporting the .uasset correctly.
Can you investigate?
